footprint: [[-1.00, -0.60], [-1.00, 0.60], [1.00, 0.60], [1.00, -0.60]]
footprint_padding: 0.0
resolution: 0.2
transform_tolerance: 0.3
inflation_layer:
  inflation_radius: 0.05
  cost_scaling_factor: 10.0
