local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.2
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /map
    first_map_only: true
    subscribe_to_updates: false
    track_unknown_space: false
